import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { MemoryDatabase } from "../db/database.js";
import { registerSaveMemory } from "./save-memory.js";
import { registerSaveMemories } from "./save-memories.js";
import { registerGetMemory } from "./get-memory.js";
import { registerGetMemories } from "./get-memories.js";
import { registerUpdateMemory } from "./update-memory.js";
import { registerUpdateMemories } from "./update-memories.js";
import { registerDeleteMemory } from "./delete-memory.js";
import { registerDeleteMemories } from "./delete-memories.js";
import { registerSearchMemories } from "./search-memories.js";
import { registerListMemories } from "./list-memories.js";
import { registerGetContextSnapshot } from "./get-context-snapshot.js";
import { registerMaintenance } from "./maintenance.js";
import { registerExportMemories } from "./export-memories.js";
import { registerImportMemories } from "./import-memories.js";
import { registerGetStats } from "./get-stats.js";
import { registerPurgeExpired } from "./purge-expired.js";
import { registerLinkMemories } from "./link-memories.js";
import { registerUnlinkMemories } from "./unlink-memories.js";
import { registerGetRelated } from "./get-related.js";
import { registerRenameTag } from "./rename-tag.js";
import { registerGetLinks } from "./get-links.js";
import { registerUpdateLink } from "./update-link.js";
import { registerBackup } from "./backup.js";
import { registerGetGraph } from "./get-graph.js";
import { registerGetHistory } from "./get-history.js";
import { registerRestoreMemory } from "./restore-memory.js";

export function registerAllTools(server: McpServer, db: MemoryDatabase): void {
  registerSaveMemory(server, db);
  registerSaveMemories(server, db);
  registerGetMemory(server, db);
  registerGetMemories(server, db);
  registerUpdateMemory(server, db);
  registerUpdateMemories(server, db);
  registerDeleteMemory(server, db);
  registerDeleteMemories(server, db);
  registerSearchMemories(server, db);
  registerListMemories(server, db);
  registerGetContextSnapshot(server, db);
  registerMaintenance(server, db);
  registerExportMemories(server, db);
  registerImportMemories(server, db);
  registerGetStats(server, db);
  registerPurgeExpired(server, db);
  registerLinkMemories(server, db);
  registerUnlinkMemories(server, db);
  registerGetRelated(server, db);
  registerRenameTag(server, db);
  registerGetLinks(server, db);
  registerUpdateLink(server, db);
  registerBackup(server, db);
  registerGetGraph(server, db);
  registerGetHistory(server, db);
  registerRestoreMemory(server, db);
}
